---
title: "McKellar et al. supplemental table and figures"
format: 
  pdf:    
    include-in-header: 
      text: '\pagenumbering{gobble}'
crossref:
  fig-title: Figure S     # (default is "Figure")
  tbl-title: Table S     # (default is "Table")
---

```{r load_saved, echo=FALSE, message=FALSE,warning=FALSE}
library(tidyverse)
library(kableExtra)
fig1 <- readRDS("figures/Figure_s1.rds")
fig2 <- readRDS("figures/figure_s2.rds")
fig3 <- readRDS("figures/figure_s3.rds")
fig4 <- readRDS("figures/figure_s4.rds")

tab1a <- read_csv("cross_validation/selected_cross_validation_comparison.csv")
tab1b <- read_csv("cross_validation/cv_summary_simple.csv")

tab1 <- tab1b %>% 
  select(model,mean_loo) %>% 
  filter(model != "core_spei") %>% 
  arrange(-mean_loo)

tab1a1 <- data.frame(model = tab1$model,
                     t_dif = c(NA,
                               tab1a$t_dif_naoi1,
                               tab1a$t_dif_cov,
                               tab1a$t_dif_base))

model_names <- data.frame(model_type = c("base",
                                         "cov",
                                         "core_naoi1",
                                         "core"),
                          model_name = c("Base",
                                    "Climate",
                                    "Climate-plus-core [NAOI 1-year lagged]",
                                    "Climate-plus-core"))
table1 <- tab1 %>% 
  left_join(tab1a1) %>% 
  left_join(model_names,
            by = c("model" = "model_type")) %>% 
  relocate(model_name, mean_loo, t_dif) %>% 
  mutate(mean_loo = signif(mean_loo,4),
         t_dif = signif(t_dif,2)) %>% 
  select(-model) %>% 
  rename(Model = model_name,
         `Mean lppd` = mean_loo,
         `t-statistic pairwise difference from best model` = t_dif)


```

```{r tableS1, echo=FALSE, message=FALSE,warning=FALSE}

kable(table1,
      caption = "The summary results of a 10-fold targeted cross-validation where all observations from a random sample of years are predicted when left-out of the model training set. The best model is the same as the model identified as the best by the approximate leave-one-out comparison reported in the main paper.")

```

{{< pagebreak >}}

```{r figs1, echo=FALSE, message=FALSE,warning=FALSE, fig.dpi=300, fig.cap="Covariate effects from all 5 models."}


print(fig1)
```

{{< pagebreak >}}

```{r fig2, echo=FALSE, message=FALSE,warning=FALSE, fig.dpi=300, fig.cap="Local effect of 3-month SPEI (top plot) and 3-month SPEI 1-year lagged (bottom plot) from the Climate [spring+sprin 1-year lagged] model. The general pattern of strongest positive effects in the core of the range is very similar to the pattern for the combined effect of local 15-month SPEI that had higher predictive accuracy."}


print(fig2)


```

{{< pagebreak >}}

```{r fig3, echo=FALSE, message=FALSE,warning=FALSE, fig.dpi=300, fig.height=8,fig.cap="Local effect of NAOI 1-year lagged (12-18 months before BBS counts) from the Climate-plus-core [NAOI 1-year lagged] model. The spatial pattern in effects is largely opposite to the pattern for the NAOI from the preceding winter (1-6 months before BBS counts): negative in the core of the species' range and positive in the southern perimeter."}


print(fig3)  
```

{{< pagebreak >}}

```{r fig4, echo=FALSE, message=FALSE,warning=FALSE, fig.dpi=300, fig.height=8, fig.cap="Population trajectories and trends from all of the models compared in the paper. Long-term trends are very similar across all models, and the short-term effects from all covariate models (all models except the base model) are all very similar."}


print(fig4)  
```
